# Generated by Django 4.1 on 2022-11-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="phone",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
